import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { WatchlistProvider } from "@/context/WatchlistContext";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Stock Ping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className}  antialiased`}
      >
        <WatchlistProvider>
          <Header/>
          <hr/>
          {children}
        </WatchlistProvider>
      </body>
    </html>
  );
}
